version: "3.9"

services:
  mariadb:
    image: mariadb:11.7.2-ubi9
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: esonero
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql:Z
      - ./mariadb_init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "8003:8003"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=esonero

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "8001:80"
    depends_on:
      backend:
        condition: service_started