version: "3.9"

services:
  mariadb:
    image: mariadb:11.7.2-ubi9
    container_name: mariadb-toystore
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: toy_store
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql:Z
      - ./mariadb_init:/docker-entrypoint-initdb.d:ro

  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "8003:8000"
    depends_on:
      - mariadb
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=toy_store

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend